server:
  port: 8090
spring:
  application:
    name: kzou-user-service-consumer2
eureka:
  instance:
    hostname: kzou-user-service-consumer2
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
    register-with-eureka: true
    fetch-registry: true
